### ISSUE TITLE
[REQ] K4 Zenith

### ISSUE THREAD

**Issue by Toxiic57** [PorcusorulMagic/K4-System-Time-Website#1]
Hi.

Is it possible to make it work with the new K4-Zenith Time Stats  ?

Thanks.

**Comment by PorcusorulMagic** [comment]
I abandoned the project. Sry

**Comment by PorcusorulMagic** [comment]
I abandoned the project. Sry

**Comment by itsAudioo** [comment]
> Hi.
> 
> Is it possible to make it work with the new K4-Zenith Time Stats ?
> 
> Thanks.

You can use gamecms.org it has all zenith modules
